import "./globals.css";

import { Lato as Sans, Merriweather as Serif } from "next/font/google";

import React from "react";
import type { Metadata } from "next";

import ThemeProvider from "@/components/ui/ThemeProvider";

const sans = Sans({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-sans",
});

const serif = Serif({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`h-screen dark:bg-dark bg-light dark:text-light text-dark overflow-hidden`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
